default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  pool: 5
  username: ubuntu
  password: password

development:
  <<: *default
  database: sampler_development

test:
  <<: *default
  database: sampler_test
  
production:
  <<: *default
  encoding: unicode
  database: sampler